"""Fraud signal definitions and weights."""

HIGH = 40
MEDIUM = 20
LOW = 10


SIGNALS: list[dict[str, object]] = [
    {
        "id": "trade_advance_payment",
        "category": "trade",
        "label": "선입금·예약금 유도",
        "weight": HIGH,
        "scam_type": "선입금 먹튀 사기",
        "why": "물건이나 일감을 제공하기 전 돈부터 보내게 한 뒤 연락을 끊는 수법",
        "patterns": [
            r"선입금",
            r"예약금",
            r"계약금",
            r"먼저\s*(입금|송금|보내)",
            r"(입금|송금).{0,8}먼저",
        ],
    },
    {
        "id": "trade_external_channel",
        "category": "trade",
        "label": "외부채널 유도",
        "weight": MEDIUM,
        "scam_type": "플랫폼 보호 회피 사기",
        "why": "신고·결제 보호가 어려운 외부 채널로 유도해 피해 추적을 어렵게 만드는 수법",
        "patterns": [
            r"텔레그램",
            r"텔레",
            r"카톡",
            r"오픈채팅",
            r"문자\s*(주세요|연락)",
            r"외부\s*(채널|메신저)",
        ],
    },
    {
        "id": "trade_safe_payment_avoidance",
        "category": "trade",
        "label": "안전결제 회피",
        "weight": MEDIUM,
        "scam_type": "안전결제 회피형 거래 사기",
        "why": "구매자 보호 장치를 피하고 계좌이체만 요구해 환불·분쟁 대응을 어렵게 만드는 수법",
        "patterns": [
            r"안전결제\s*(안|못|불가|거절)",
            r"안전거래\s*(안|못|불가|거절)",
            r"직거래만",
            r"계좌이체만",
        ],
    },
    {
        "id": "trade_too_cheap",
        "category": "trade",
        "label": "시세대비 저가",
        "weight": MEDIUM,
        "scam_type": "미끼 가격 거래 사기",
        "why": "비정상적으로 낮은 가격으로 급한 결정을 유도한 뒤 선입금이나 외부 거래로 끌고 가는 수법",
        # TODO: Compare against market price data when an external price source exists.
        "patterns": [
            r"시세보다\s*(싸게|저렴)",
            r"급처",
            r"반값",
            r"초특가",
            r"파격가",
        ],
    },
    {
        "id": "trade_shipping_only",
        "category": "trade",
        "label": "택배강요+직거래거부",
        "weight": MEDIUM,
        "scam_type": "비대면 배송 거래 사기",
        "why": "직접 확인할 기회를 차단하고 택배 거래만 요구해 물건 미발송 피해로 이어질 수 있는 수법",
        "patterns": [
            r"택배만",
            r"택배\s*(거래|가능)",
            r"직거래\s*(불가|안\s*돼|안됩니다|못해)",
            r"직거래.{0,8}(불가|거부)",
        ],
    },
    {
        "id": "trade_urgency",
        "category": "trade",
        "label": "긴급성 조성",
        "weight": LOW,
        "scam_type": "긴급 결제 유도 사기",
        "why": "오늘만 가능하다는 식으로 시간을 압박해 검증 없이 결제하게 만드는 수법",
        "patterns": [
            r"오늘만",
            r"선착순",
            r"급하게",
            r"마감\s*임박",
            r"빨리\s*(거래|입금|연락)",
        ],
    },
    {
        "id": "trade_suspicious_url",
        "category": "trade",
        "label": "의심 URL",
        "weight": HIGH,
        "scam_type": "피싱 링크 유도",
        "why": "외부 링크로 접속시켜 결제 정보나 계정 정보를 빼내거나 악성 페이지로 유도하는 수법",
        "patterns": [
            r"https?://[^\s]+",
            r"bit\.ly/[^\s]+",
            r"tinyurl\.com/[^\s]+",
            r"링크.{0,8}(접속|확인)",
        ],
    },
    {
        "id": "trade_no_verification",
        "category": "trade",
        "label": "본인인증·배지 없음",
        "weight": LOW,
        "scam_type": "신원 미확인 거래 위험",
        "why": "판매자 신원 확인이 어렵다는 점을 이용해 피해 발생 후 추적을 어렵게 만들 수 있는 유형",
        # TODO: Use platform profile metadata when available; text alone is conservative.
        "patterns": [
            r"본인인증\s*(없|안)",
            r"인증\s*(없|안\s*했)",
            r"배지\s*(없|미보유)",
        ],
    },
    {
        "id": "participation_money_mule",
        "category": "scam_participation",
        "label": "자금 중개/대리 이체",
        "weight": HIGH,
        "scam_type": "보이스피싱 자금 세탁(계좌 중개)",
        "why": "범죄 자금을 내 계좌로 받아 이체·인출·전달하게 해 자금세탁 공범으로 만드는 수법",
        "patterns": [
            r"송금된\s*(금액|돈)\s*확인",
            r"다른\s*계좌로\s*이체",
            r"현금으로\s*인출",
            r"인출해\s*전달",
            r"환전\s*대행",
            r"건당\s*수수료",
            r"건당\s*[0-9~\-]+\s*%?\s*수수료",
            r"이체\s*수수료",
        ],
    },
    {
        "id": "participation_illegal_device",
        "category": "scam_participation",
        "label": "불법 장비 설치",
        "weight": HIGH,
        "scam_type": "불법 중계기 설치 사기",
        "why": "집에 통신 장비를 설치하게 해 보이스피싱·스팸 발신 중계지로 악용하는 수법",
        "patterns": [
            r"장비\s*설치",
            r"장비.{0,10}집에\s*설치",
            r"중계기",
            r"공유기\s*설치",
            r"모뎀\s*설치",
            r"단말기\s*설치",
            r"기기\s*연결만",
            r"전원.{0,5}인터넷만\s*연결",
        ],
    },
    {
        "id": "participation_pickup_delivery",
        "category": "scam_participation",
        "label": "물품 수거·전달책",
        "weight": HIGH,
        "scam_type": "보이스피싱 수거책 사기",
        "why": "현금·상품권·귀금속을 대신 결제·수거·전달하게 해 범죄 수익 운반책으로 만드는 수법",
        "patterns": [
            r"구매\s*대행",
            r"대신\s*결제",
            r"픽업",
            r"퀵으로\s*전달",
            r"지정\s*장소로\s*전달",
            r"지정\s*장소.{0,5}인도",
            r"골드바",
            r"상품권\s*대량",
            r"명품\s*대리구매",
            r"회사\s*체크카드",
        ],
    },
    {
        "id": "participation_body_photo_request",
        "category": "scam_participation",
        "label": "신체 노출 사진 요구",
        "weight": HIGH,
        "scam_type": "몸캠피싱·협찬 보증금 사기",
        "why": "노출성 사진이나 보증금을 요구한 뒤 사진을 협박에 쓰거나 환불 없이 잠적하는 수법",
        "patterns": [
            r"신체\s*부위\s*촬영",
            r"속옷.{0,8}(착용\s*컷|라인|촬영)",
            r"란제리.{0,8}(착용\s*컷|라인|촬영)",
            r"노출\s*사진",
            r"얼굴\s*안\s*나와도",
        ],
    },
    {
        "id": "participation_paid_work_program",
        "category": "scam_participation",
        "label": "작업용 유료 프로그램 결제",
        "weight": HIGH,
        "scam_type": "가짜 작업 프로그램 결제 사기",
        "why": "업무용 프로그램이나 라이선스 비용을 먼저 결제하게 한 뒤 환불·급여 지급 없이 사라지는 수법",
        "patterns": [
            r"전용\s*프로그램\s*설치",
            r"정산\s*프로그램",
            r"작업\s*프로그램\s*라이선스",
            r"프로그램\s*비용\s*결제",
            r"첫\s*급여에\s*환불",
            r"라이선스\s*비용\s*결제",
        ],
    },
    {
        "id": "participation_name_signature_rental",
        "category": "scam_participation",
        "label": "명의/서명 대여",
        "weight": HIGH,
        "scam_type": "명의 도용 대출 사기",
        "why": "동행·서명 명목으로 구직자 명의의 할부/캐피탈 대출을 실행시켜 빚을 떠넘기는 수법",
        "patterns": [
            r"서명만",
            r"서명만\s*같이",
            r"머릿수",
            r"머릿수\s*채우",
            r"명의로\s*계약",
            r"비서\s*역할\s*대행",
            r"출고\s*검수\s*동행",
            r"계약\s*시\s*동행",
            r"동행.{0,12}(서명|머릿수|명의|계약|캐피탈|할부|대출)",
            r"(서명|머릿수|명의|계약|캐피탈|할부|대출).{0,12}동행",
            r"할부.{0,5}대출\s*동행",
            r"(할부|대출)\s*동행",
            r"캐피탈",
        ],
    },
    {
        "id": "participation_account_rental",
        "category": "scam_participation",
        "label": "계정 대여·탈취",
        "weight": HIGH,
        "scam_type": "불법 홍보 계정 악용",
        "why": "내 SNS 계정으로 불법 도박·성인물을 홍보하게 하거나 계정을 탈취해 영구정지·수사 대상이 되게 하는 수법",
        "patterns": [
            r"아이디.{0,3}비밀번호\s*제공",
            r"아이디.{0,3}비번\s*(제공|넘겨)",
            r"계정\s*대여",
            r"로그인\s*정보\s*넘기면",
            r"타(인)?\s*계정.{0,20}(좋아요|댓글|대리\s*포스팅)",
            r"대리\s*포스팅.{0,20}(좋아요|댓글|타(인)?\s*계정)",
            r"(댓글|좋아요)\s*작업",
            r"원고\s*회사\s*제공\s*복붙",
        ],
    },
    {
        "id": "participation_signup_referral",
        "category": "scam_participation",
        "label": "계정 가입·추천 유도",
        "weight": MEDIUM,
        "scam_type": "유료가입·추천인 먹튀",
        "why": "작업자 등록이나 본인 인증을 명목으로 가입비·추천인 실적을 챙긴 뒤 일을 주지 않는 수법",
        "patterns": [
            r"작업자\s*등록",
            r"본인\s*인증\s*절차",
            r"유료\s*가입",
            r"추천인",
            r"초기\s*등록비",
        ],
    },
    {
        "id": "job_money_request",
        "category": "job",
        "label": "금전 요구-보증금/교육비",
        "weight": HIGH,
        "scam_type": "채용 전 비용 요구 사기",
        "why": "정상 채용과 달리 보증금·교육비·라이선스 비용을 먼저 내게 해 금전 피해를 만드는 수법",
        "patterns": [
            r"보증금",
            r"보증금\s*먼저\s*입금",
            r"협찬\s*보증금",
            r"먼저\s*입금하면\s*환불",
            r"교육비",
            r"가입비",
            r"초기\s*(등록비|비용)",
            r"비용\s*결제",
            r"라이선스\s*비용",
            r"먼저\s*(입금|송금|결제)",
        ],
    },
    {
        "id": "job_identity_account_request",
        "category": "job",
        "label": "신분증·계좌·통장사본 요구",
        "weight": HIGH,
        "scam_type": "개인정보·계좌 악용 사기",
        "why": "채용 전 민감 정보를 요구해 대포통장·명의도용·추가 금융 피해로 이어질 수 있는 수법",
        "patterns": [
            r"신분증",
            r"주민등록증",
            r"계좌번호",
            r"통장\s*사본",
            r"체크카드",
            r"otp",
        ],
    },
    {
        "id": "job_external_messenger",
        "category": "job",
        "label": "외부메신저 유도",
        "weight": MEDIUM,
        "scam_type": "외부 메신저 유도형 채용 사기",
        "why": "공고 플랫폼 밖으로 이동시켜 신고·증거 보존을 어렵게 하고 추가 요구를 이어가는 수법",
        "patterns": [
            r"텔레그램",
            r"텔레",
            r"카톡",
            r"카카오톡\s*채널",
            r"오픈채팅",
            r"담당자\s*링크",
            r"pf\.kakao\.com",
            r"외부\s*(메신저|채널)",
        ],
    },
    {
        "id": "job_high_income",
        "category": "job",
        "label": "고수익 보장",
        "weight": MEDIUM,
        "scam_type": "고수익 미끼 알바 사기",
        "why": "쉽고 높은 보수를 내세워 검증을 느슨하게 만든 뒤 위험한 역할이나 선결제를 요구하는 수법",
        "patterns": [
            r"고수익",
            r"인센티브",
            r"수익\s*보장",
            r"일당\s*[0-9]+\s*만",
            r"주급\s*[0-9]+\s*만",
            r"월\s*[0-9]+백",
            r"건별\s*지급",
            r"건당\s*[0-9]+",
            r"수수료를\s*지급",
            r"하는\s*만큼",
            r"버는\s*구조",
            r"돈만\s*(주겠다|주겠|드립니다|지급)",
            r"재택.{0,8}고수익",
        ],
    },
    {
        "id": "job_instant_payment",
        "category": "job",
        "label": "비현실적 즉시보상",
        "weight": MEDIUM,
        "scam_type": "즉시 보상 미끼 사기",
        "why": "당일 지급을 내세워 의심스러운 업무를 빠르게 수락하게 만드는 수법",
        "patterns": [
            r"당일\s*지급",
            r"당일\s*정산",
            r"즉시\s*지급",
            r"현금\s*당일\s*지급",
        ],
    },
    {
        "id": "job_personal_info_pre_request",
        "category": "job",
        "label": "개인정보 선요구",
        "weight": MEDIUM,
        "scam_type": "채용 전 개인정보 수집 사기",
        "why": "면접·계약 전 개인정보를 먼저 요구해 명의도용이나 추가 사기 표적으로 삼는 수법",
        "patterns": [
            r"성함.{0,5}나이\s*남겨",
            r"신분\s*정보\s*기입",
            r"본인\s*인증\s*절차",
            r"채용\s*전.{0,10}개인정보",
            r"개인정보.{0,10}먼저",
        ],
    },
    {
        "id": "job_vague_work",
        "category": "job",
        "label": "업무 모호",
        "weight": LOW,
        "scam_type": "업무내용 은폐형 알바 사기",
        "why": "구체적인 업무를 숨긴 채 간단하다고만 설명해 실제 위험한 역할을 뒤늦게 요구하는 수법",
        "requires_any": [
            "job_high_income",
            "job_instant_payment",
            "participation_money_mule",
            "participation_illegal_device",
            "participation_pickup_delivery",
            "participation_body_photo_request",
            "participation_paid_work_program",
            "participation_name_signature_rental",
            "participation_account_rental",
            "participation_signup_referral",
        ],
        "patterns": [
            r"간단한\s*(업무|작업)",
            r"단순\s*(업무|작업)",
            r"쉬운\s*(업무|작업)",
            r"누구나\s*가능",
            r"초보\s*가능",
            r"초보\s*환영",
            r"연결만",
            r"연결하면\s*됩니다",
            r"설치만",
            r"동행",
            r"대리\s*포스팅",
            r"작업자\s*등록",
        ],
    },
    {
        "id": "job_no_interview",
        "category": "job",
        "label": "면접없이 즉시채용",
        "weight": LOW,
        "scam_type": "무검증 즉시채용 사기",
        "why": "정상적인 확인 절차 없이 바로 채용한다고 하며 위험한 요구를 빠르게 진행하는 수법",
        "patterns": [
            r"면접\s*(없|없이|불필요)",
            r"즉시\s*채용",
            r"바로\s*(채용|근무)",
            r"당일\s*(채용|근무)",
        ],
    },
    {
        "id": "job_self_safety_claim",
        "category": "job",
        "label": "자가 안전성 주장",
        "weight": LOW,
        "scam_type": "정상 업체 사칭 사기",
        "why": "안전·정상 업체라고 강조해 의심을 낮춘 뒤 위험한 요구를 정당화하는 수법",
        "requires_any": [
            "participation_money_mule",
            "participation_illegal_device",
            "participation_pickup_delivery",
            "participation_body_photo_request",
            "participation_paid_work_program",
            "participation_name_signature_rental",
            "participation_account_rental",
            "participation_signup_referral",
        ],
        "patterns": [
            r"안전하다",
            r"안전합니다",
            r"법무법인",
            r"정식\s*등록\s*대행업체",
            r"사업자등록증\s*보유",
            r"정상\s*기업",
        ],
    },
]
